### ISSUE TITLE
Solid community values

### ISSUE THREAD

**Issue by eduardoinnorway** [solid/community#55]
I suggest that we setup our values as a community. Strong values is the backbone of any good organisation/company. I really like what we have going now and it is important that we establish our values now early on before we become to big.

EXAMPLE:

We the Solid community values:

- Skilled and humble
- Privacy matters
- We assist to grow
- A web we want is our passion

Values should reflect for example "What we are" as type of people, "What do we care for", "How do we do it" and "Why do we do it".

For me Values is the most important thing that I work with when I coach new teams and everyone should be involved in having their saying to this. So maybe we should start with a open online session that anyone can join in and work our way from there.

https://www.forbes.com/sites/garypeterson/2013/08/14/three-reasons-why-values-matter-and-im-not-talking-the-money-kind/#71f50edd1d93

https://www.glennsmithcoaching.com/7-reasons-core-values-important/

**Comment by Mitzi-Laszlo** [comment]
Thanks Eduardo, great suggestion. 

Here's some draft ideas that I'd like to add to the pool of suggestions: 

Self Determination: People and legal entities should be given the tools for self-determination. Self-determination involves the app user controling data generated as a result of using an application, rather than the developer or owner of the application. Data control includes deciding where the data is stored as well as who sees what data, for what purpose, when. No individual should make a decision on behalf of another individual without consultation and ensuring that the invidually is equiped with the necessary infomration to make an informed decisoin on the matter at hand that does not take advantage of convenience nudging.

Interoperability: Data should be interoperable to ensure that individuals or legal entities are able to self determine independently of the technical possibilities. Technical hurdles should not be used as an excuse to not provide interoperability.

Equal Access: There should be equal access to the web by all individuals both for consumption and creation. Although, for example, development, may take education, this education should be freely available and accecible by all.

Sourcing: It should be easy to find the source of a piece of data so that one can judge the trustworthiness of the data.

Public Value: The web should serve humanity to become more functional through collaboration leading toward mutual benefit. The long term public interest should be given priority over the short term private interest.

?Connecting: An individual or legal entity should be able to connect data they control to the data others control (what is a religious institution or government body insists on including a person as a member of a group that means they could be persecuted? Could this conflict with self-determination? Right to be forgotten? Right to disconnect?)

**Comment by megoth** [comment]
I would also love a point about the value of choosing technologies that have a positive impact on the collective, ecological footprint that we have on our world. But I'm struggling with a good way of vocalizing this =/

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/community/blob/master/Solid-values.md
